# Generated by Django 5.0.6 on 2024-05-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustoIndireto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Custo Indireto",
                "verbose_name_plural": "Custos Indiretos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("salario", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unidade_medida",
                    models.CharField(
                        choices=[
                            ("g", "gramas"),
                            ("kg", "quilogramas"),
                            ("ml", "mililitros"),
                            ("l", "litros"),
                        ],
                        max_length=2,
                        verbose_name="Preço por unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente",
                "verbose_name_plural": "Ingredientes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Lojas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endereco", models.CharField(max_length=150)),
                ("aluguel", models.DecimalField(decimal_places=2, max_digits=10)),
                ("agua", models.DecimalField(decimal_places=2, max_digits=10)),
                ("luz", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "custo",
                    models.DecimalField(
                        decimal_places=2, default=0.0, editable=False, max_digits=10
                    ),
                ),
                (
                    "numero_por_dia",
                    models.IntegerField(
                        default=1, verbose_name="Pratos vendidos por dia"
                    ),
                ),
                ("funcionario", models.ManyToManyField(to="pricing.funcionario")),
            ],
            options={
                "verbose_name": "Loja",
                "verbose_name_plural": "Lojas",
                "ordering": ["endereco"],
            },
        ),
        migrations.CreateModel(
            name="QuantidadeIngrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pricing.ingrediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quantidade de Ingrediente",
                "verbose_name_plural": "Quantidades de Ingredientes",
                "ordering": ["ingrediente"],
            },
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "custo",
                    models.DecimalField(
                        decimal_places=2, default=0.0, editable=False, max_digits=10
                    ),
                ),
                (
                    "valor_venda",
                    models.DecimalField(
                        decimal_places=2, default=0.0, editable=False, max_digits=10
                    ),
                ),
                (
                    "margem_lucro",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "ingredientes",
                    models.ManyToManyField(
                        through="pricing.QuantidadeIngrediente",
                        to="pricing.ingrediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="quantidadeingrediente",
            name="receita",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pricing.receita"
            ),
        ),
    ]
