# Generated by Django 5.0.6 on 2024-05-26 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lojas",
            name="funcionario",
        ),
        migrations.AddField(
            model_name="funcionario",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo?"),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="loja_associada",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funcionario",
                to="pricing.lojas",
                verbose_name="Lojas",
            ),
        ),
        migrations.AlterField(
            model_name="custoindireto",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="custoindireto",
            name="valor",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Valor"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="salario",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Salário"
            ),
        ),
        migrations.AlterField(
            model_name="ingrediente",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="ingrediente",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Preço por peso"
            ),
        ),
        migrations.AlterField(
            model_name="ingrediente",
            name="unidade_medida",
            field=models.CharField(
                choices=[
                    ("g", "gramas (G)"),
                    ("kg", "quilogramas (Kg)"),
                    ("ml", "mililitros (Ml)"),
                    ("l", "litros (L)"),
                    ("un", "unidades"),
                ],
                max_length=2,
                verbose_name="Unidade de Medida",
            ),
        ),
        migrations.AlterField(
            model_name="lojas",
            name="agua",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Água"
            ),
        ),
        migrations.AlterField(
            model_name="lojas",
            name="aluguel",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Aluguel"
            ),
        ),
        migrations.AlterField(
            model_name="lojas",
            name="custo",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=10,
                verbose_name="Custo",
            ),
        ),
        migrations.AlterField(
            model_name="lojas",
            name="endereco",
            field=models.CharField(max_length=150, verbose_name="Endereço"),
        ),
        migrations.AlterField(
            model_name="lojas",
            name="luz",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Luz"
            ),
        ),
        migrations.AlterField(
            model_name="quantidadeingrediente",
            name="quantidade",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Quantidade"
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="custo",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=10,
                verbose_name="Custo",
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="ingredientes",
            field=models.ManyToManyField(
                through="pricing.QuantidadeIngrediente",
                to="pricing.ingrediente",
                verbose_name="Ingredientes",
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="margem_lucro",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Margem de Lucro (%)"
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="receita",
            name="valor_venda",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=10,
                verbose_name="Valor de Venda",
            ),
        ),
    ]
