# Generated by Django 5.0.6 on 2024-05-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0002_remove_lojas_funcionario_funcionario_ativo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="loja_associada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funcionario",
                to="pricing.lojas",
                verbose_name="Lojas",
            ),
        ),
    ]
