# Generated by Django 5.0.6 on 2024-05-27 02:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0003_alter_funcionario_loja_associada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lojas",
            name="custo",
        ),
    ]
